name: ci

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker version
        run: docker --version || sudo docker --version

      - name: Show user info
        run: id
        
  docker-install:
    runs-on: ubuntu-latest
    steps:
      - name: docker install
        run: sudo apt install docker.io -y

      - name: enable docker
        run: sudo systemctl enable docker
        

  configure:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Add ubuntu to docker group
        run: sudo usermod -aG docker $user

      - name: Verify groups
        run: groups ubuntu

  verify:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker access
        run: docker ps || echo "Docker requires logout/login"

          
          
